import { canonicalUserShellAssets } from "../../lib/bardoctor/app-shell";

export function GET(): Response {
  return new Response(`<!doctype html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Ручной ввод — BarDoctor</title>
  ${canonicalUserShellAssets()}<link rel="stylesheet" href="/inventory-onboarding.css?v=phase5"><link rel="stylesheet" href="/venue-switcher.css?v=20260826-venue-identity-v297"><script src="/venue-switcher.js?v=20260826-venue-identity-v297" defer></script><link rel="stylesheet" href="/sales-journal.css?v=sales-ux1"><script src="/sales-journal.js?v=sales-ux1" defer></script><script src="/sales-entry.js?v=sales-ux1" defer></script></head>
  <body class="sales-entry-shell" data-bd-parent-route="/sales-import"><header><a href="/sales-import">← Продажи</a><h1 id="entry-title">Ручной ввод</h1><div class="bd-standalone-venue-host" data-bd-venue-host></div><nav class="sales-navigation" aria-label="Разделы продаж"><a href="/sales-import">Журнал</a><a href="/cashier">Касса</a><a id="shifts-nav" href="/sales-entry?view=shifts">Смены</a><a id="manual-nav" href="/sales-entry">Ручной ввод</a><a href="/sales-import?view=import">Импорт</a></nav></header><main><p id="entry-explanation">Внесите операцию вручную. Проверка покажет выручку и складской расход перед подтверждением.</p>
  <p id="notice" role="status" aria-live="polite">Загрузка…</p><div id="work" hidden>
  <form id="sale"><label>Смена<select id="shift"><option value="">Без смены</option></select></label><div id="lines"></div><div class="actions"><button id="add-line" type="button">Добавить позицию</button><button type="submit">Проверить продажу</button></div></form>
  <section id="preview" hidden><h2>Проверка продажи</h2><div id="quote"></div><div class="actions"><button id="post">Подтвердить продажу</button><button id="discard">Не сохранять</button></div></section>
  <section id="shift-actions"><h2>Кассовые смены</h2><p>Смены для проведения чеков POS и ручных продаж. Общий раздел «Смены» содержит также операционные итоги заведения.</p><form id="open-shift"><label>Название новой смены<input id="shift-name" required maxlength="160"></label><button type="submit">Открыть смену</button></form><p>Закрытие смены завершает ввод продаж и возвратов в неё.</p><div id="shifts"></div></section>
  <section id="event-actions" hidden><h2>Действия продажи</h2><div id="events"></div></section><p><a href="/sales-import">Все продажи — в едином журнале</a></p></div></main></body></html>`, {headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store","Content-Security-Policy":"default-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'self'"}});
}
