import assert from 'node:assert/strict';
import test from 'node:test';
import { lifecycleRuntime } from './helpers/lifecycle-runtime';

const profile = (name: string) => ({ name, businessType: 'Бар', country: 'Молдова', city: 'Кишинёв', currency: 'MDL' });
const context = (id: number) => ({ params: Promise.resolve({ id: String(id) }) });
test('archive current/last, login, restore same venue; create after last deletion; deny foreign owner', async t => {
  const r = await lifecycleRuntime(); t.after(r.close);
  const owner = await r.register('archive@isolated.test'), other = await r.register('other@isolated.test');
  r.sqlite.prepare('UPDATE accounts SET restaurant_json=? WHERE id=?').run(JSON.stringify(profile('First')), owner.userId);
  const staleIdentity = await r.api.auth.authenticateIdentityRequest(r.request(owner, '/')); assert.ok(staleIdentity);
  const call = (method: string, body: unknown, user = owner) => r.api.venue[method](r.request(user, `/api/venues/${owner.activeVenueId}`, method, body), context(owner.activeVenueId));
  assert.equal((await call('PATCH', { status: 'archived' }, other)).status, 403);
  assert.equal((await call('PATCH', { status: 'archived' })).status, 200);
  assert.equal(await r.api.auth.authenticateRequest(r.request(owner, '/')), null);
  const login = await r.api.login.POST(new Request('https://isolated.test/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: owner.email, password: 'Isolated-Test-Password-123!' }) }));
  const signedIn = await login.json() as typeof owner; assert.equal(signedIn.activeVenueId, null);
  const archive = await (await r.api.account.GET(r.request(signedIn, '/api/users/lifecycle'))).json() as { venues: { status: string }[] };
  assert.equal(archive.venues[0].status, 'archived');
  assert.equal((await call('PATCH', { status: 'active' }, signedIn)).status, 200);
  assert.equal(r.sqlite.prepare('SELECT count(*) n FROM venues WHERE data_account_id=?').get(owner.userId)?.n, 1);
  assert.equal((await call('DELETE', { confirmation: 'First' }, other)).status, 403);
  assert.equal((await call('DELETE', { confirmation: 'wrong' })).status, 400);
  assert.equal((await call('DELETE', { confirmation: 'First' })).status, 200);
  await r.api.auth.ensureOwnerVenue(staleIdentity);
  assert.equal((await call('DELETE', { confirmation: 'First' })).status, 200);
  assert.equal(r.sqlite.prepare('SELECT count(*) n FROM venues WHERE id=?').get(owner.activeVenueId)?.n, 0);
  const identity = await r.api.auth.authenticateIdentityRequest(r.request(owner, '/')); assert.ok(identity);
  await r.api.auth.membershipsForAccount(identity);
  assert.equal(r.sqlite.prepare('SELECT count(*) n FROM venues WHERE data_account_id=?').get(owner.userId)?.n, 0, 'login must not recreate deleted initial venue');
  const created = await r.api.venues.POST(r.request(owner, '/api/venues', 'POST', profile('New')));
  assert.equal(created.status, 201, JSON.stringify(await created.clone().json()));
  assert.equal(r.sqlite.prepare('SELECT count(*) n FROM venues WHERE id=?').get(other.activeVenueId)?.n, 1);
});
test('storage/database failure has no false success; retry finishes scoped deletion', async t => {
  const r = await lifecycleRuntime(); t.after(r.close); const owner = await r.register('failure@isolated.test');
  const secondResponse = await r.api.venues.POST(r.request(owner, '/api/venues', 'POST', profile('Second')));
  const second = ((await secondResponse.json()) as { venue: { id: number } }).venue;
  const dataId = r.sqlite.prepare('SELECT data_account_id id FROM venues WHERE id=?').get(second.id)!.id;
  r.objects.set(`purchases/${dataId}/invoice`, 'private'); r.objects.set(`purchases/${owner.userId}/keep`, 'other venue');
  const remove = () => r.api.venue.DELETE(r.request(owner, `/api/venues/${second.id}`, 'DELETE', { confirmation: 'Second' }), context(second.id));
  r.failDatabase(); assert.equal((await remove()).status, 503);
  assert.equal(r.sqlite.prepare('SELECT status FROM venues WHERE id=?').get(second.id)?.status, 'active');
  r.failStorage(true); assert.equal((await remove()).status, 503);
  assert.equal(r.sqlite.prepare('SELECT status FROM venues WHERE id=?').get(second.id)?.status, 'deleting');
  const stale = r.request(owner, '/'); stale.headers.set('X-Venue-Id', String(second.id)); assert.equal(await r.api.auth.authenticateRequest(stale), null);
  r.failStorage(false); assert.equal((await remove()).status, 200);
  assert.equal(r.objects.has(`purchases/${dataId}/invoice`), false); assert.equal(r.objects.has(`purchases/${owner.userId}/keep`), true);
});
test('venue deletion waits for a leased member notification and preserves another venue notification', async t => {
  const r = await lifecycleRuntime(); t.after(r.close); const owner = await r.register('jobs@isolated.test'), member = await r.register('jobs-member@isolated.test');
  const insert = r.sqlite.prepare("INSERT INTO notification_jobs(account_id,venue_id,source_type,category,dedupe_key,title,message,target_url,target_at,timezone,status,leased_at) VALUES (?,?,'test','tasks',?,'Test','Test','/home','2099-01-01T00:00:00Z','UTC','dispatching',?)");
  insert.run(member.userId, owner.activeVenueId, 'delete-job', new Date().toISOString());
  insert.run(member.userId, member.activeVenueId, 'keep-job', new Date().toISOString());
  const remove = () => r.api.venue.DELETE(r.request(owner, `/api/venues/${owner.activeVenueId}`, 'DELETE', { confirmation: `Заведение №${owner.activeVenueId}` }), context(owner.activeVenueId));
  assert.equal((await remove()).status, 503);
  assert.equal(r.sqlite.prepare('SELECT status FROM venues WHERE id=?').get(owner.activeVenueId)?.status, 'deleting');
  r.sqlite.prepare("UPDATE notification_jobs SET status='cancelled' WHERE dedupe_key='delete-job'").run();
  assert.equal((await remove()).status, 200);
  assert.equal(r.sqlite.prepare("SELECT count(*) n FROM notification_jobs WHERE dedupe_key='delete-job'").get()?.n, 0);
  assert.equal(r.sqlite.prepare("SELECT status FROM notification_jobs WHERE dedupe_key='keep-job'").get()?.status, 'dispatching');
});
test('account last owner requires separate confirmations; old sessions revoked; registration is fresh', async t => {
  const r = await lifecycleRuntime(); t.after(r.close);
  const owner = await r.register('delete@isolated.test'), other = await r.register('survivor@isolated.test');
  r.sqlite.prepare('UPDATE accounts SET restaurant_json=? WHERE id=?').run(JSON.stringify(profile('Owned')), owner.userId);
  r.sqlite.prepare("INSERT INTO domain_data(account_id,store_key,data_json) VALUES (?,'test-private','[1]')").run(owner.userId);
  const body = { confirmation: 'УДАЛИТЬ АККАУНТ', password: 'Isolated-Test-Password-123!', deleteVenues: { [owner.activeVenueId]: 'Owned' } };
  const remove = (data: unknown) => r.api.account.DELETE(r.request(owner, '/api/users/lifecycle', 'DELETE', data));
  assert.equal((await remove({ ...body, password: 'wrong' })).status, 403);
  assert.equal((await remove({ ...body, deleteVenues: {} })).status, 409);
  assert.equal((await remove(body)).status, 200);
  assert.equal(await r.api.auth.authenticateIdentityRequest(r.request(owner, '/')), null);
  const oldBootstrap = await r.api.bootstrap.POST(r.request(owner, '/api/auth/bootstrap', 'POST'));
  assert.equal(oldBootstrap.status, 401, 'revoked session must not reimport legacy account');
  assert.equal(r.sqlite.prepare("SELECT count(*) n FROM accounts WHERE id=? AND account_kind='user'").get(owner.userId)?.n, 0);
  assert.equal(r.sqlite.prepare('SELECT count(*) n FROM domain_data WHERE account_id=?').get(owner.userId)?.n, 0);
  assert.ok(await r.api.auth.authenticateIdentityRequest(r.request(other, '/')));
  const fresh = await r.register(owner.email); assert.notEqual(fresh.userId, owner.userId); assert.notEqual(fresh.activeVenueId, owner.activeVenueId);
  assert.equal(await r.api.lifecycle.identityWasDeleted(owner.email), true);
  assert.equal(r.sqlite.prepare("SELECT count(*) n FROM domain_data WHERE account_id=? AND store_key='test-private'").get(fresh.userId)?.n, 0);
});
test('shared venue and foreign membership survive deleting account including original data container', async t => {
  const r = await lifecycleRuntime(); t.after(r.close);
  const owner = await r.register('shared@isolated.test'), other = await r.register('coowner@isolated.test');
  const workspace = r.sqlite.prepare('SELECT workspace_id id FROM venues WHERE id=?').get(owner.activeVenueId)!.id;
  r.sqlite.prepare("INSERT INTO workspace_memberships(workspace_id,account_id,role) VALUES (?,?,'owner')").run(workspace, other.userId);
  r.sqlite.prepare("INSERT INTO venue_memberships(venue_id,account_id,role) VALUES (?,?,'owner')").run(owner.activeVenueId, other.userId);
  r.sqlite.prepare("INSERT INTO venue_memberships(venue_id,account_id,role) VALUES (?,?,'manager')").run(other.activeVenueId, owner.userId);
  r.sqlite.prepare("INSERT INTO domain_data(account_id,store_key,data_json) VALUES (?,'shared-history','[42]')").run(owner.userId);
  const response = await r.api.account.DELETE(r.request(owner, '/api/users/lifecycle', 'DELETE', { confirmation: 'УДАЛИТЬ АККАУНТ', password: 'Isolated-Test-Password-123!' }));
  assert.equal(response.status, 200);
  assert.equal(r.sqlite.prepare('SELECT count(*) n FROM venues').get()?.n, 2);
  assert.equal(r.sqlite.prepare("SELECT data_json FROM domain_data WHERE account_id=? AND store_key='shared-history'").get(owner.userId)?.data_json, '[42]');
  assert.equal(r.sqlite.prepare('SELECT created_by_account_id id FROM venues WHERE id=?').get(owner.activeVenueId)?.id, other.userId);
  const request = r.request(other, '/'); request.headers.set('X-Venue-Id', String(owner.activeVenueId));
  assert.ok(await r.api.auth.authenticateRequest(request));
  assert.equal(r.sqlite.prepare('SELECT count(*) n FROM venue_memberships WHERE account_id=?').get(owner.userId)?.n, 0);
  const lastVenueName = `Заведение №${owner.activeVenueId}`;
  const deleted = await r.api.venue.DELETE(r.request(other, `/api/venues/${owner.activeVenueId}`, 'DELETE', { confirmation: lastVenueName }), context(owner.activeVenueId));
  assert.equal(deleted.status, 200, JSON.stringify(await deleted.clone().json()));
  assert.equal(await r.api.lifecycle.identityWasDeleted(owner.email), true, 'deleting the shared data container must retain the legacy resurrection guard');
  assert.equal(r.sqlite.prepare("SELECT count(*) n FROM domain_data WHERE account_id=?").get(owner.userId)?.n, 0);
});
