import test from 'node:test';
import assert from 'node:assert/strict';
import {nativeWorkerRuntime} from './helpers/native-worker-runtime.mjs';
test('Phase4B compiled Worker/native D1: critical queue, exact URL context and authoritative day/stock correction',{timeout:120000},async t=>{
 const r=await nativeWorkerRuntime();t.after(r.close);
 for(const key of ['bd_finance_revenue','bd_operational_reports_v1','bd_sales_events_v1','bd_sales_documents','bd_cases','bd_equipment','bd_equipment_history','bd_equipment_work_orders','bd_finance_expenses','bd_inventory_snapshots','bd_opening_stock_v1','bd_stock_movements','bd_tasks','bd_action_tasks','bd_decisions'])await r.put(key,[]);
 await r.put('bd_cases',[{id:'native-critical',venueId:1,priority:'critical',status:'open'}]);
 await r.put('bd_tasks',[{id:'native-task',issueKey:'safety',priority:'critical',title:'Проверить безопасное состояние',approvalStatus:'approved',status:'in_progress',deadline:'2026-01-01'}]);
 await r.put('bd_finance_revenue',[{id:'native-cash',venueId:1,date:'2026-10-02',revenueSource:'sales_events_v1',closingStatus:'closed',revenue:200,currency:'MDL'}]);
 await r.put('bd_sales_events_v1',[{id:'native-sale',venueId:1,businessDate:'2026-10-02',revenueRowId:'native-cash',status:'POSTED',source:'POS_API',revenue:200,currency:'MDL'}]);
 await r.put('bd_assortment_v1',{menuItems:[],recipes:[],nomenclature:[{id:'native-stock',key:'product:native',productKey:'product:native',name:'QA Stock',kind:'stock',active:true,venueId:1,unit:'pcs',unitModelVersion:4}],stockBalances:[{productKey:'product:native',venueId:1,unit:'pcs',current:2,minimum:5,openingDocumentId:'native-opening'}]});
 await r.put('bd_opening_stock_v1',[{id:'native-opening',venueId:1,status:'confirmed',createdAt:'2026-10-01T12:00:00Z',anchorBoundary:{movements:[]},items:[{id:'native-line',productKey:'product:native',unit:'pcs',quantity:2}]}]);
 const body=async response=>{assert.ok(response.ok,await response.clone().text());return response.json()};
 const initial=await body(await r.call('/api/business-health')),queue=initial.data.businessHealthSnapshot.managementQueue;
 assert.equal(queue[0].linkedTaskId,'native-task');assert.equal(queue[1].caseId,'native-critical');assert.ok(!queue[1].target.path.startsWith('/equipment'));
 const day=queue.find(row=>row.verificationKind==='day'),stock=queue.find(row=>row.verificationKind==='stock');assert.ok(day&&stock);
 const verify=id=>r.call('/api/business-health/verify?actionId='+encodeURIComponent(id));
 const before=(await r.db.prepare('SELECT * FROM domain_data ORDER BY store_key').all()).results;assert.equal((await body(await verify(stock.managementId))).verification.result,'ACTIVE');assert.deepEqual((await r.db.prepare('SELECT * FROM domain_data ORDER BY store_key').all()).results,before);
 assert.equal((await verify(stock.managementId.replace('health:1:','health:999:'))).status,404);
 await body(await r.call('/api/shifts/close','POST',{sectionsVersion:1,venueId:1,shiftCloseId:'native-report-save',shiftId:'native-cash',revenueRecord:{date:'2026-10-02',payrollBreakdown:{total:20}},writeOffItems:[]}));
 const after=await body(await verify(day.managementId));assert.equal(after.verification.result,'CONDITION_CLEARED');assert.equal(after.verification.resolutionAuthority,'CANONICAL_SERVER_REREAD');assert.notEqual(after.verification.inputRevision,initial.data.businessHealthSnapshot.inputRevision);
 const created=await body(await r.call('/api/inventory/counts','POST',{venueId:1,action:'create',date:'2026-10-03',scope:{type:'all'}}));
 await body(await r.call('/api/inventory/counts','POST',{venueId:1,action:'save',id:created.inventory.id,items:created.inventory.items.map(row=>({...row,actual:8}))}));
 assert.equal((await body(await verify(stock.managementId))).verification.result,'ACTIVE');
 await body(await r.call('/api/inventory/counts','POST',{venueId:1,action:'finalize',id:created.inventory.id}));
 assert.equal((await body(await verify(stock.managementId))).verification.result,'CONDITION_CLEARED');
 const reloaded=await body(await r.call('/api/business-health'));assert.ok(!reloaded.data.businessHealthSnapshot.managementQueue.some(row=>[day.managementId,stock.managementId].includes(row.managementId)));
 assert.equal(r.outbound(),0);
});
