import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import os from 'node:os';
const root=fileURLToPath(new URL('../',import.meta.url));
test('access and taxonomy patches replay without duplicate helpers or losing final handlers',t=>{
 const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'bd-tech-access-replay-'));t.after(()=>fs.rmSync(temporary,{recursive:true,force:true}));
 for(const folder of ['public','scripts','lib','app'])fs.cpSync(path.join(root,folder),path.join(temporary,folder),{recursive:true});
 fs.copyFileSync(path.join(root,'tsconfig.json'),path.join(temporary,'tsconfig.json'));fs.symlinkSync(path.join(root,'node_modules'),path.join(temporary,'node_modules'),'dir');
 const bundlePath=path.join(temporary,'public/assets/index-BQGspy0I.js');
 const scripts=['patch-menu-consumption-sot-v418.mjs','patch-menu-edit-actions-v435.mjs','patch-legacy-consumption-normalization-v436.mjs','patch-edit-form-actions-v438.mjs','patch-editor-standard-v439.mjs','patch-tech-card-access-v440.mjs','patch-menu-taxonomy-v440.mjs'];
 const apply=()=>{for(const [file,args] of [['patch-curated-doctor-phase4c.mjs',['--restore']],['patch-management-actions-phase4b.mjs',['--restore']],['patch-management-cost-phase4a.mjs',['--restore']],...scripts.map(file=>[file,[]]),['patch-management-cost-phase4a.mjs',[]],['patch-management-actions-phase4b.mjs',[]],['patch-curated-doctor-phase4c.mjs',[]]]){const result=spawnSync(process.execPath,[path.join(temporary,'scripts',file),...args],{cwd:temporary,encoding:'utf8'});assert.equal(result.status,0,result.stderr)}};
 apply();const before=fs.readFileSync(bundlePath,'utf8');apply();const after=fs.readFileSync(bundlePath,'utf8');
 assert.equal(after,before);
 assert.ok(after.includes('await bdCostClientPhase4a.afterSave(bdCostSaveVenue'),'accepted server save keeps the Phase4A reread hook');
 assert.equal(after.split('/* management-cost-phase4a:start */').length-1,1);
 for(const name of ['bdEditableRecipesV440','bdExistingRecipeEditorV440','bdMenuTaxonomyRequestV440','bdIngredientReferencePatchV440'])assert.equal(after.split('function '+name+'(').length-1,1,name);
 assert.ok(after.includes('if(!c.synced||w.status==="confirmed"&&!p)'),'draft stays open on failed sync');
 assert.ok(after.includes('onClick:()=>{bdMenuCloseV435()&&bdMenuOpenRecipeV440()}'),'menu transition uses existing dirty confirmation');
 assert.ok(after.includes('bdIngredientReferenceConflictV440(p,n)||'),'conflicts block confirmation');
 assert.ok(after.includes('const bdRecipeSourceChangedV442=bdUseRecipeRefreshV442(t,r,bdTechDirtyRefV438,bdRecipeSavingRefV418,u,f)'),'editor subscribes to fresh source without remounting');
 assert.ok(after.includes('E=async p=>{if(bdRecipeSourceChangedV442)'),'both saves guard against a changed source');
 assert.ok(after.includes('resolutionStatus:bdIngredientReferenceConflictV440(p,n)?"reference_conflict":"linked_ready"'),'unit conversion does not clear an unresolved reference conflict');
});
