import test, {type TestContext} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {lifecycleRuntime} from './helpers/lifecycle-runtime';
import {salesEventFixture} from './helpers/sales-event-fixture';
import {compileFinancialClient} from './helpers/financial-client-phase7.mjs';
import {canonicalVenueTimezone, venueDate, venueClock, venueTimeFromJson} from '../lib/bardoctor/venue-time';
type Reply = { ok:boolean; code:string; event:import('../lib/bardoctor/sales-events').SalesEvent; previewHash:string; restaurant:{timezone:string}; venue:{id:number}; timezone:string; timezoneConfigured:boolean; batch:{businessDate:string} };
const evidence:Record<string,unknown>[]=[];
const local=(iso:string,zone='Europe/Chisinau')=>new Intl.DateTimeFormat('sv-SE',{timeZone:zone,dateStyle:'short',timeStyle:'medium'}).format(new Date(iso));
async function fixture(t:TestContext,now:string,timezone='Europe/Chisinau'){t.mock.timers.enable({apis:['Date'],now:Date.parse(now)});const r=await lifecycleRuntime({events:'./app/api/sales-events/route',batches:'./app/api/sales-batches/route',profile:'./app/api/restaurants/route'});t.after(r.close);const user=await r.register('timezone@isolated.test'),venue=user.activeVenueId;
r.sqlite.prepare('UPDATE accounts SET restaurant_json=? WHERE id=?').run(JSON.stringify({name:'Timezone QA',currency:'MDL',timezone}),user.userId);
const put=(key:string,value:unknown)=>r.sqlite.prepare('INSERT INTO domain_data(account_id,store_key,data_json,updated_at) VALUES (?,?,?,?) ON CONFLICT(account_id,store_key) DO UPDATE SET data_json=excluded.data_json').run(user.userId,key,JSON.stringify(value),now);
const read=(key:string)=>JSON.parse(String(r.sqlite.prepare('SELECT data_json FROM domain_data WHERE account_id=? AND store_key=?').get(user.userId,key)?.data_json??'null'));
put('bd_assortment_v1',JSON.parse(JSON.stringify(salesEventFixture().assortment).replaceAll('"venueId":1','"venueId":'+venue)));
const send=async(body:Record<string,unknown>)=>{const q=r.request(user,'/api/sales-events','POST',{venueId:venue,...body});q.headers.set('X-Venue-Id',String(venue));const response=await r.api.events.POST(q);return {status:response.status,data:await response.json<Reply>()};};
const command=(id:string,shiftId?:string,pos=false)=>({id,source:pos?'POS_API':'MANUAL_GRID',...(shiftId?{shiftId}:{}),...(pos?{payments:[{id:'p',method:'CASH',amount:20}]}:{}),lines:[{id:'l',menuItemId:'beer',quantity:1}]});
const sale=async(cmd:ReturnType<typeof command>)=>{const p=await send({action:'preview',command:cmd});assert.equal(p.status,200,JSON.stringify(p));const posted=await send({action:'post',command:cmd,previewHash:p.data.previewHash});assert.equal(posted.status,201,JSON.stringify(posted));return posted.data.event;};return {r,user,venue,put,read,send,command,sale};}
for(const [name,now,calendar,accounting] of [['summer month','2026-09-30T21:30:00Z','2026-10-01','2026-10-01'],['winter month','2026-01-31T22:30:00Z','2026-02-01','2026-02-01'],['before local midnight','2026-09-30T20:59:00Z','2026-09-30','2026-09-30']])test(name,async t=>{const f=await fixture(t,now);assert.ok(local(now).startsWith(calendar));const manual=await f.sale(f.command('manual'));assert.equal((await f.send({action:'open_shift',shiftId:'C',name:'New shift'})).status,201);const pos=await f.sale(f.command('pos','C',true));assert.equal(manual.businessDate,accounting);assert.equal(pos.businessDate,accounting);const audit=f.r.sqlite.prepare("SELECT month_key FROM audit_log WHERE account_id=? AND store_key='bd_sales_events_v1'").all(f.user.userId);assert.ok(audit.length>=3);assert.ok(audit.every(row=>row.month_key===accounting.slice(0,7)));const shifts=f.read('bd_finance_revenue');const shift=shifts.find((s:Record<string,unknown>)=>s.id==='C');assert.equal(shift.date,accounting);const client=compileFinancialClient(fs.readFileSync('public/assets/index-BQGspy0I.js','utf8'),f.read,{now,localStorage:{getItem:(key:string)=>key==='bd_active_venue_id'?String(f.venue):null}});const months=[...new Set([calendar.slice(0,7),accounting.slice(0,7)])];const monthly=Object.fromEntries(months.map(month=>[month,client.report({id:f.venue,name:'Timezone QA',currency:'MDL',accountingCurrency:'MDL',areas:[]},month,shifts,[],[],{},[]).revenue]));assert.equal(monthly[accounting.slice(0,7)],40);if(calendar.slice(0,7)!==accounting.slice(0,7))assert.equal(monthly[calendar.slice(0,7)],0);evidence.push({case:name,utc:now,local:local(now),manualDate:manual.businessDate,newPosShiftDate:pos.businessDate,shiftStartTime:shift.startTime,monthly});});
for(const [name,before,after,expected] of [['local midnight','2026-09-30T20:59:59Z','2026-09-30T21:00:01Z',409],['UTC midnight','2026-09-30T23:59:59Z','2026-10-01T00:00:01Z',201]] as const)test(name+' between preview/post',async t=>{const f=await fixture(t,before),cmd=f.command('edge');const p=await f.send({action:'preview',command:cmd});assert.equal(p.status,200);t.mock.timers.setTime(Date.parse(after));const post=await f.send({action:'post',command:cmd,previewHash:p.data.previewHash});assert.equal(post.status,expected);if(expected===409)assert.equal(post.data.code,'SALES_EVENT_PREVIEW_CHANGED');evidence.push({case:name,localBefore:local(before),localAfter:local(after),previewDate:p.data.event.businessDate,postStatus:post.status,postDate:post.data.event?.businessDate,code:post.data.code});});
test('closed September allows new local October shift',async t=>{const f=await fixture(t,'2026-09-30T21:30:00Z');f.put('bd_month_closings',[{monthKey:'2026-09',status:'closed'}]);for(const action of ['open_shift','preview']){const response=await f.send(action==='open_shift'?{action,shiftId:'C',name:'October'}:{action,command:f.command('october')});assert.equal(response.status,action==='open_shift'?201:200);evidence.push({case:'closed old month',local:local(new Date().toISOString()),action,status:response.status,code:response.data.code});}});
test('overnight shift preserves shift day and preview across UTC midnight',async t=>{const f=await fixture(t,'2026-09-30T20:00:00Z');assert.equal((await f.send({action:'open_shift',shiftId:'C',name:'Overnight'})).status,201);const cmd=f.command('overnight','C',true),p=await f.send({action:'preview',command:cmd});assert.equal(p.status,200);t.mock.timers.setTime(Date.parse('2026-10-01T00:30:00Z'));const post=await f.send({action:'post',command:cmd,previewHash:p.data.previewHash});assert.equal(post.status,201);assert.equal(post.data.event.businessDate,'2026-09-30');evidence.push({case:'overnight intended',local:local(new Date().toISOString()),businessDate:post.data.event.businessDate,postStatus:post.status});});

test('American venues use own calendar, clock and month independent of browser or server timezone',async t=>{
 for(const [zone,now,date,clock] of [['America/New_York','2026-10-01T00:30:00Z','2026-09-30','20:30'],['America/Los_Angeles','2026-10-01T06:30:00Z','2026-09-30','23:30']])await t.test(zone,async sub=>{const f=await fixture(sub,now,zone);const sale=await f.sale(f.command('west'));assert.equal(sale.businessDate,date);assert.equal(sale.timezone,zone);assert.equal((await f.send({action:'open_shift',shiftId:'C',name:'West'})).status,201);const row=f.read('bd_finance_revenue').find((r:Record<string,unknown>)=>r.id==='C');assert.equal(row.date,date);assert.equal(row.startTime,clock);const client=compileFinancialClient(fs.readFileSync('public/assets/index-BQGspy0I.js','utf8'),f.read,{now,localStorage:{getItem:(k:string)=>k==='bd_active_venue_id'?String(f.venue):null}});for(const [month,total] of [['2026-09',20],['2026-10',0]])assert.equal(client.report({id:f.venue,name:'QA',currency:'MDL',accountingCurrency:'MDL',areas:[]},month,f.read('bd_finance_revenue'),[],[],{},[]).revenue,total);});
});
test('timezone validation, DST, explicit UTC and deterministic legacy fallback',()=>{
 for(const bad of ['','UTC+3','+03:00','Invalid/City',null,42])assert.equal(canonicalVenueTimezone(bad),undefined);
 assert.equal(canonicalVenueTimezone('Europe/Chisinau'),'Europe/Chisinau');assert.equal(canonicalVenueTimezone('America/New_York'),'America/New_York');
 assert.deepEqual(venueTimeFromJson('{}'),{timezone:'UTC',timezoneConfigured:false});assert.deepEqual(venueTimeFromJson('{"timezone":"UTC"}'),{timezone:'UTC',timezoneConfigured:true});
 assert.equal(venueClock('2026-03-08T06:59:00Z','America/New_York'),'01:59');assert.equal(venueClock('2026-03-08T07:01:00Z','America/New_York'),'03:01');
 assert.equal(venueClock('2026-11-01T05:30:00Z','America/New_York'),'01:30');assert.equal(venueClock('2026-11-01T06:30:00Z','America/New_York'),'01:30');
 assert.equal(venueDate('2026-03-29T01:01:00Z','Europe/Chisinau'),'2026-03-29');
});
test('profile save validates timezone, preserves omitted zone and isolates accounts; history is immutable',async t=>{
 const f=await fixture(t,'2026-09-30T21:30:00Z');const posted=await f.sale(f.command('history'));const before=JSON.stringify(f.read('bd_sales_events_v1'));const save=async(body:Record<string,unknown>,user=f.user)=>f.r.api.profile.POST(f.r.request(user,'/api/restaurants','POST',body));
 const invalid=await save({name:'QA',timezone:'Invalid/City'});assert.equal(invalid.status,400);assert.equal((await invalid.json<Reply>()).code,'INVALID_VENUE_TIMEZONE');
 const changed=await save({name:'QA',currency:'MDL',timezone:'America/New_York'});assert.equal(changed.status,200);assert.equal((await changed.json<Reply>()).restaurant.timezone,'America/New_York');
 const partial=await save({name:'QA renamed',currency:'MDL'});assert.equal((await partial.json<Reply>()).restaurant.timezone,'America/New_York');
 assert.equal(JSON.stringify(f.read('bd_sales_events_v1')),before);assert.equal(posted.businessDate,'2026-10-01');
 const other=await f.r.register('other@isolated.test');const denied=f.r.request(other,'/api/sales-events','POST',{venueId:f.venue,action:'open_shift',shiftId:'foreign',name:'Foreign'});denied.headers.set('X-Venue-Id',String(f.venue));assert.notEqual((await f.r.api.events.POST(denied)).status,201);
 const second=await f.r.api.venues.POST(f.r.request(f.user,'/api/venues','POST',{name:'LA',businessType:'bar',country:'USA',city:'Los Angeles',currency:'MDL',timezone:'America/Los_Angeles'}));assert.equal(second.status,201);const secondVenue=(await second.json<Reply>()).venue.id;
 const q=f.r.request(f.user,'/api/sales-events');q.headers.set('X-Venue-Id',String(secondVenue));assert.equal((await (await f.r.api.events.GET(q)).json<Reply>()).timezone,'America/Los_Angeles');const original=f.r.request(f.user,'/api/sales-events');original.headers.set('X-Venue-Id',String(f.venue));assert.equal((await (await f.r.api.events.GET(original)).json<Reply>()).timezone,'America/New_York');
});
test('configured timezone change invalidates unshifted preview; existing shift retains captured timezone/date',async t=>{
 const f=await fixture(t,'2026-10-01T10:00:00Z');assert.equal((await f.send({action:'open_shift',shiftId:'C',name:'C'})).status,201);const cmd=f.command('pending');const quoted=await f.send({action:'preview',command:cmd});assert.equal(quoted.status,200);
 f.r.sqlite.prepare('UPDATE accounts SET restaurant_json=? WHERE id=?').run(JSON.stringify({name:'QA',currency:'MDL',timezone:'America/New_York'}),f.user.userId);
 const post=await f.send({action:'post',command:cmd,previewHash:quoted.data.previewHash});assert.equal(post.status,409);assert.equal(post.data.code,'SALES_EVENT_PREVIEW_CHANGED');const inShift=await f.sale(f.command('sameShift','C',true));assert.equal(inShift.timezone,'Europe/Chisinau');assert.equal(inShift.businessDate,'2026-10-01');assert.equal((await f.send({action:'close_shift',shiftId:'C'})).status,201);const closed=f.read('bd_finance_revenue').find((row:Record<string,unknown>)=>row.id==='C');assert.equal(closed.endTime,'13:00');assert.equal(closed.closingStatus,'closed');
});
test('unconfigured legacy profile remains UTC and exposes setup state; import default follows configured venue',async t=>{
 const f=await fixture(t,'2026-09-30T21:30:00Z','');const old=await f.sale(f.command('legacy'));assert.equal(old.businessDate,'2026-09-30');const q=f.r.request(f.user,'/api/sales-events');const payload=await(await f.r.api.events.GET(q)).json<Reply>();assert.equal(payload.timezoneConfigured,false);assert.equal(payload.timezone,'UTC');
 f.r.sqlite.prepare('UPDATE accounts SET restaurant_json=? WHERE id=?').run(JSON.stringify({name:'QA',currency:'MDL',timezone:'Europe/Chisinau'}),f.user.userId);
 const draft=await f.r.api.batches.POST(f.r.request(f.user,'/api/sales-batches','POST',{venueId:f.venue,action:'import_text',text:'Beer 1'}));assert.equal(draft.status,201);assert.equal((await draft.json<Reply>()).batch.businessDate,'2026-10-01');
});
