#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ "${SITES_ENV_READY:-}" != "1" ]]; then
  exec "${script_dir}/sites-env.sh" -- "$0" "$@"
fi

command -v timeout >/dev/null || {
  echo "build-verified.sh requires GNU timeout." >&2
  exit 69
}

vinext="${SITES_PROJECT_ROOT}/node_modules/.bin/vinext"
if [[ ! -x "${vinext}" ]]; then
  echo "vinext is unavailable. Run npm run install:ci and wait for it to finish before building." >&2
  exit 69
fi

echo "Running bounded vinext build..."
node "${script_dir}/patch-inventory-layer-v246.mjs"
node "${script_dir}/patch-inventory-delete-v270.mjs"
node "${script_dir}/patch-writeoff-workflow-v271.mjs"
node "${script_dir}/patch-shift-writeoffs-v272.mjs"
node "${script_dir}/patch-navigation-qa-v268.mjs"
node "${script_dir}/patch-auth-bootstrap-state-v274.mjs"
node "${script_dir}/patch-auth-bootstrap-profile-ready-v274.mjs"
node "${script_dir}/patch-sales-consumption-v275.mjs"
node "${script_dir}/patch-profile-v280.mjs"
node "${script_dir}/patch-profile-v281.mjs"
node "${script_dir}/patch-venue-identity-v297.mjs"
node "${script_dir}/patch-business-health-snapshot-v284.mjs"
node "${script_dir}/patch-owner-uat-v285.mjs"
node "${script_dir}/patch-owner-uat-v286.mjs"
node "${script_dir}/patch-owner-uat-v287.mjs"
node "${script_dir}/patch-owner-uat-v288.mjs"
node "${script_dir}/patch-owner-uat-v289.mjs"
node "${script_dir}/patch-owner-uat-v290.mjs"
node "${script_dir}/patch-owner-uat-v291.mjs"
node "${script_dir}/patch-owner-uat-v292.mjs"
node "${script_dir}/patch-owner-uat-v293.mjs"
node "${script_dir}/patch-owner-uat-v294.mjs"
node "${script_dir}/patch-owner-uat-v295.mjs"
node "${script_dir}/patch-business-health-ux-v332.mjs"
node "${script_dir}/patch-canonical-taxonomy-workflow-v336.mjs"
node "${script_dir}/patch-canonical-taxonomy-integrations-v337.mjs"
node "${script_dir}/patch-canonical-taxonomy-reuse-v338.mjs"
node "${script_dir}/patch-canonical-taxonomy-freshness-v339.mjs"
node "${script_dir}/patch-canonical-taxonomy-postbuild-v340.mjs"
node "${script_dir}/patch-startup-runtime-hardening-v342.mjs"
node "${script_dir}/patch-startup-performance-v343.mjs"
node "${script_dir}/patch-authoritative-home-startup-v344.mjs"
node "${script_dir}/patch-authenticated-home-shell-v345.mjs"
node "${script_dir}/patch-branded-startup-handoff-v346.mjs"
node "${script_dir}/patch-coherent-startup-v347.mjs"
node "${script_dir}/patch-ios-launch-screen-v348.mjs"
node "${script_dir}/patch-single-ready-home-v349.mjs"
node "${script_dir}/patch-menu-nomenclature-flow-v350.mjs"
node "${script_dir}/patch-menu-nomenclature-link-v352.mjs"
node "${script_dir}/patch-catalog-workflow-ux-v353.mjs"
node "${script_dir}/patch-modal-workspace-v354.mjs"
node "${script_dir}/patch-publication-readiness-v355.mjs"
node "${script_dir}/patch-seamless-startup-v356.mjs"
node "${script_dir}/patch-bounded-startup-handoff-v357.mjs"
node "${script_dir}/patch-purchase-accounting-v359.mjs"
node "${script_dir}/patch-taxonomy-manager-ux-v360.mjs"
node "${script_dir}/patch-optional-subcategory-v361.mjs"
node "${script_dir}/patch-classification-ux-v362.mjs"
node "${script_dir}/patch-alphabetical-taxonomy-v363.mjs"
node "${script_dir}/patch-taxonomy-action-sheet-v364.mjs"
node "${script_dir}/patch-nested-sections-v365.mjs"
node "${script_dir}/patch-nomenclature-catalog-route-v366.mjs"
node "${script_dir}/patch-purchase-category-options-v367.mjs"
node "${script_dir}/patch-tech-card-catalog-picker-v368.mjs"
node "${script_dir}/patch-nomenclature-uat-v369.mjs"
node "${script_dir}/patch-quick-add-purchase-v372.mjs"
timeout \
  --signal=TERM \
  --kill-after="${SITES_BUILD_KILL_AFTER:-10s}" \
  "${SITES_BUILD_TIMEOUT:-3m}" \
  "${vinext}" build

node "${script_dir}/patch-inventory-layer-v246.mjs"
node "${script_dir}/patch-inventory-delete-v270.mjs"
node "${script_dir}/patch-writeoff-workflow-v271.mjs"
node "${script_dir}/patch-shift-writeoffs-v272.mjs"
node "${script_dir}/patch-navigation-qa-v268.mjs"
node "${script_dir}/patch-auth-bootstrap-state-v274.mjs"
node "${script_dir}/patch-auth-bootstrap-profile-ready-v274.mjs"
node "${script_dir}/patch-sales-consumption-v275.mjs"
node "${script_dir}/patch-profile-v280.mjs"
node "${script_dir}/patch-profile-v281.mjs"
node "${script_dir}/patch-venue-identity-v297.mjs"
node "${script_dir}/patch-business-health-snapshot-v284.mjs"
node "${script_dir}/patch-owner-uat-v285.mjs"
node "${script_dir}/patch-owner-uat-v286.mjs"
node "${script_dir}/patch-owner-uat-v287.mjs"
node "${script_dir}/patch-owner-uat-v288.mjs"
node "${script_dir}/patch-owner-uat-v289.mjs"
node "${script_dir}/patch-owner-uat-v290.mjs"
node "${script_dir}/patch-owner-uat-v291.mjs"
node "${script_dir}/patch-owner-uat-v292.mjs"
node "${script_dir}/patch-owner-uat-v293.mjs"
node "${script_dir}/patch-owner-uat-v294.mjs"
node "${script_dir}/patch-owner-uat-v295.mjs"
node "${script_dir}/patch-business-health-ux-v332.mjs"
node "${script_dir}/patch-canonical-taxonomy-workflow-v336.mjs"
node "${script_dir}/patch-canonical-taxonomy-integrations-v337.mjs"
node "${script_dir}/patch-canonical-taxonomy-reuse-v338.mjs"
node "${script_dir}/patch-canonical-taxonomy-freshness-v339.mjs"
node "${script_dir}/patch-canonical-taxonomy-postbuild-v340.mjs"
node "${script_dir}/patch-startup-runtime-hardening-v342.mjs"
node "${script_dir}/patch-startup-performance-v343.mjs"
node "${script_dir}/patch-authoritative-home-startup-v344.mjs"
node "${script_dir}/patch-authenticated-home-shell-v345.mjs"
node "${script_dir}/patch-branded-startup-handoff-v346.mjs"
node "${script_dir}/patch-coherent-startup-v347.mjs"
node "${script_dir}/patch-ios-launch-screen-v348.mjs"
node "${script_dir}/patch-single-ready-home-v349.mjs"
node "${script_dir}/patch-menu-nomenclature-flow-v350.mjs"
node "${script_dir}/patch-menu-nomenclature-link-v352.mjs"
node "${script_dir}/patch-catalog-workflow-ux-v353.mjs"
node "${script_dir}/patch-modal-workspace-v354.mjs"
node "${script_dir}/patch-publication-readiness-v355.mjs"
node "${script_dir}/patch-seamless-startup-v356.mjs"
node "${script_dir}/patch-bounded-startup-handoff-v357.mjs"
node "${script_dir}/patch-purchase-accounting-v359.mjs"
node "${script_dir}/patch-taxonomy-manager-ux-v360.mjs"
node "${script_dir}/patch-optional-subcategory-v361.mjs"
node "${script_dir}/patch-classification-ux-v362.mjs"
node "${script_dir}/patch-alphabetical-taxonomy-v363.mjs"
node "${script_dir}/patch-taxonomy-action-sheet-v364.mjs"
node "${script_dir}/patch-nested-sections-v365.mjs"
node "${script_dir}/patch-nomenclature-catalog-route-v366.mjs"
node "${script_dir}/patch-purchase-category-options-v367.mjs"
node "${script_dir}/patch-tech-card-catalog-picker-v368.mjs"
node "${script_dir}/patch-nomenclature-uat-v369.mjs"
node "${script_dir}/patch-quick-add-purchase-v372.mjs"
"${script_dir}/validate-artifact.sh"
