import { waitForSalesHostReads } from '../tests/helpers/sales-navigation-settled';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve, extname } from 'node:path';
import { createRequire } from 'node:module';
import { chromium, webkit } from 'playwright-core';
import { closingFixture } from '../tests/helpers/month-close-fixture';
import { barDoctorResponse } from '../app/bar-doctor-response';
const require=createRequire(import.meta.url),{resolveBrowserExecutable,chromiumArgs}=require('./browser-runtime.cjs');
const engine=process.env.BD_DERIVED_BROWSER==='webkit'?webkit:chromium;
const browser=await engine.launch({headless:true,...(engine===chromium?{executablePath:await resolveBrowserExecutable(chromium.executablePath()),args:chromiumArgs}:{})});
const out=`outputs/derived-metrics-phase3a8/${engine===webkit?'webkit':'chromium'}`;mkdirSync(out,{recursive:true});const results:unknown[]=[];
try{for(const width of [390,820,1280]){
 const r=await closingFixture();
 const server=createServer(async(req,res)=>{try{const url=new URL(req.url||'/',`http://${req.headers.host}`),chunks:Buffer[]=[];for await(const chunk of req)chunks.push(Buffer.from(chunk));const body=Buffer.concat(chunks),key=url.pathname.match(/^\/api\/store\/([^/]+)$/)?.[1];const routes:Record<string,string>={'/api/month-close':'closing','/api/auth/bootstrap':'bootstrap','/api/restaurants/me':'restaurant','/api/users/me':'users','/api/venues':'venues','/api/store':'bulkStore','/api/assortment/overview':'overview','/api/business-health':'health'};const name=key?'store':routes[url.pathname];let response:Response;
 if(name)response=await r.api[name][req.method||'GET'](new Request(url,{method:req.method,headers:req.headers as HeadersInit,...(body.length?{body}:{})}),{params:Promise.resolve({key})} as never);
 else if(['/reports','/home','/login'].includes(url.pathname))response=barDoctorResponse();
 else{const file=resolve('public','.'+url.pathname);response=file.startsWith(resolve('public'))&&existsSync(file)?new Response(readFileSync(file),{headers:{'Content-Type':({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'} as Record<string,string>)[extname(file)]||'application/octet-stream'}}):new Response(null,{status:404});}
 res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch(error){console.error(error);res.writeHead(500);res.end('fixture failure');}});
 await new Promise<void>(done=>server.listen(0,'127.0.0.1',done));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const context=await browser.newContext({viewport:{width,height:900}});const errors:string[]=[];
 try{
 await context.exposeBinding('__bdPerfObserve',()=>{});await context.addInitScript({path:resolve('scripts/qa/sales-navigation-probe.js')});
 await context.addInitScript(({email,token,venueId})=>{localStorage.setItem('bd_session',email);localStorage.setItem('bd_session_token',token);localStorage.setItem('bd_active_venue_id',String(venueId));},{...r.user,venueId:r.venueId});
 await context.route('**/assets/index-BQGspy0I*.js*',async route=>{const response=await route.fetch(),text=await response.text();assert.equal(text,readFileSync('public/assets/index-BQGspy0I.js','utf8'));await route.fulfill({response,body:text+`\nwindow.__phase8={reviews:D7,cache:()=>xr("bd_month_closings"),reopen:async()=>{const value=(await bdMonthRequestPhase3a8("/api/month-close?monthKey=2026-09")).closing;return qr("bd_month_closings",[{...value,status:"reopened",reopenedAt:new Date().toISOString()}])},mount:props=>{const node=document.createElement('div');document.body.appendChild(node);const root=PW.createRoot(node);root.render(i.jsx(bdMonthClosingWizard,{...props,onClose:()=>root.unmount(),onNavigate:()=>{},onClosePeriod:value=>bdSaveVerifiedMonthPhase3a8(value,props.settings.venueId,[],()=>{})}));window.__phase8Root=root;return true}};`});});
 const page=await context.newPage();const settled=async()=>{const status=await page.evaluate(async()=>{const response=await fetch('/api/business-health',{headers:{'X-Session-Email':localStorage.getItem('bd_session')||'','X-Session-Token':localStorage.getItem('bd_session_token')||'','X-Venue-Id':localStorage.getItem('bd_active_venue_id')||''}});await response.json();return response.status});assert.equal(status,200);await waitForSalesHostReads(page);};page.on('response',response=>{if(response.url().includes('/api/month-close'))void response.json().then(body=>console.log(JSON.stringify({width,status:response.status(),code:body.code,eligible:body.eligible}))).catch(()=>{});});page.on('pageerror',error=>errors.push(error.message));await page.clock.setFixedTime(new Date('2026-10-03T12:00:00Z'));await page.goto(base+'/reports');await page.waitForLoadState('networkidle');await page.waitForFunction(()=>Boolean((window as unknown as {__phase8:unknown}).__phase8));
 const metric=await page.evaluate(()=>{const api=(window as unknown as {__phase8:{reviews:(rows:object[])=>{avgRating:number;analyzedCount:number;negativeDenominator:number}}}).__phase8;return api.reviews([{date:'2026-09-02',rating:5,aiStatus:'done',sentiment:'positive',topics:['service']},{date:'2026-09-02',rating:null,aiStatus:'pending'}])});assert.equal(metric.avgRating,5);assert.equal(metric.analyzedCount,1);assert.equal(metric.negativeDenominator,1);
 const preview=await(await r.get()).json();assert.equal(preview.eligible,true);
 const mount=async()=>{await page.evaluate(({report,venueId})=>(window as unknown as {__phase8:{mount:(props:object)=>void}}).__phase8.mount({open:true,monthKey:'2026-09',report,revenues:[],expenses:[],settings:{venueId,id:venueId,inventorySections:['bar']},closure:null}),{report:preview.report,venueId:r.venueId});await page.getByRole('dialog',{name:'Мастер закрытия месяца'}).waitFor();await page.getByText('Проверяем данные месяца…').waitFor({state:'hidden'});await page.getByRole('dialog',{name:'Мастер закрытия месяца'}).locator('nav button').first().waitFor();};
 const confirm=async()=>{const dialog=page.getByRole('dialog',{name:'Мастер закрытия месяца'});for(const [index,label]of [[1,'Я проверил оплаты поставщикам и остальные расходы'],[4,'Списания'],[5,'Я проверил ФОТ, налоги и коммунальные услуги']]as const){await dialog.locator('nav button').nth(index).click();if(index===4){const buttons=dialog.locator('main button');await buttons.filter({hasText:/Я |Подтверждаю|Списания.*провер/}).last().click()}else await dialog.getByRole('button',{name:label,exact:true}).click();}await dialog.locator('nav button').nth(7).click();await dialog.getByRole('button',{name:'Подтверждаю, что данные проверены и период можно закрыть',exact:true}).click();const button=dialog.getByRole('button',{name:'Подтвердить и закрыть период',exact:true});assert.equal(await button.isEnabled(),true);await button.click();};
 await mount();r.seed('bd_finance_expenses',[{id:'changed',venueId:r.venueId,date:'2026-09-02',amount:40,category:'rent',currency:'MDL'}]);await confirm();await page.getByRole('alert').filter({hasText:'Данные месяца изменились'}).waitFor();assert.equal(r.sqlite.prepare("SELECT count(*) n FROM domain_data WHERE store_key='bd_month_closings'").get()!.n,0);await page.screenshot({path:`${out}/${width}-conflict.png`,fullPage:true});
 await page.getByRole('button',{name:'Закрыть мастер',exact:true}).click();await mount();await confirm();await page.getByText('Итог закрыт по проверенному набору данных.').waitFor();const stored=await(await r.get()).json();assert.equal(stored.evidenceStatus,'VERIFIED');assert.equal(stored.closing.snapshot.finalProfit,304);await page.screenshot({path:`${out}/${width}-verified.png`,fullPage:true});
 const cache=await page.evaluate(()=>(window as unknown as {__phase8:{cache:()=>{venueId:number;snapshot:{finalProfit:number}}[]}}).__phase8.cache());assert.equal(cache[0].venueId,r.venueId);assert.equal(cache[0].snapshot.finalProfit,304);assert.equal(await page.evaluate(()=>localStorage.getItem('bd_month_closings')),null);
 await settled();await page.reload();await page.waitForLoadState('networkidle');assert.equal((await(await r.get()).json()).closing.snapshot.finalProfit,304);await settled();const reopened=await page.evaluate(()=>(window as unknown as {__phase8:{reopen:()=>Promise<boolean>}}).__phase8.reopen());assert.equal(reopened,true);assert.equal(r.sqlite.prepare("SELECT data_json FROM domain_data WHERE store_key='bd_month_closings'").get()!.data_json!.toString().includes('\"status\":\"reopened\"'),true);
 // Real venue switch through request headers: the old closing cannot be read.
 await settled();const foreign=await r.register(`switch-${width}@isolated.test`);const switched=await page.evaluate(async({id})=>{localStorage.setItem('bd_active_venue_id',String(id));const response=await fetch('/api/month-close?monthKey=2026-09',{headers:{'X-Session-Email':localStorage.getItem('bd_session')||'','X-Session-Token':localStorage.getItem('bd_session_token')||'','X-Venue-Id':String(id)}});return{status:response.status,body:await response.json()};},{id:foreign.activeVenueId});assert.equal(switched.status,401);assert.equal(JSON.stringify(switched.body).includes('304'),false);assert.deepEqual(errors,[]);
 results.push({width,status:'PASS',staleConflict:true,verifiedClose:true,reload:true,venueSwitch:true,pageErrors:errors});
 }catch(error){const page=context.pages()[0];if(page){await page.screenshot({path:`${out}/${width}-failure.png`,fullPage:true});writeFileSync(`${out}/${width}-failure.html`,await page.content());}throw error;}finally{await context.close();await new Promise<void>(done=>server.close(()=>done()));r.close();}
}}finally{await browser.close();writeFileSync(`${out}/results.json`,JSON.stringify(results,null,2));}console.log(JSON.stringify(results));
