import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFileSync,existsSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {chromium} from 'playwright-core';
import {costFixture} from '../tests/helpers/management-cost-fixture';
import {barDoctorResponse} from '../app/bar-doctor-response';
const require=createRequire(import.meta.url),{resolveBrowserExecutable}=require('./browser-runtime.cjs');
const browser=await chromium.launch({headless:true,executablePath:await resolveBrowserExecutable(chromium.executablePath()),args:['--no-sandbox','--disable-setuid-sandbox']});
const clientHash=createHash('sha256').update(readFileSync('public/assets/index-BQGspy0I.js')).digest('hex');
const out='outputs/management-cost-phase4a';mkdirSync(out,{recursive:true});const results:unknown[]=[];
const widths=process.env.BD_COST_WIDTH?[Number(process.env.BD_COST_WIDTH)]:[390,820,1280];
try{for(const width of widths){
 const r=await costFixture();r.assortment.menuItems.push({...r.assortment.menuItems[0],id:'water-z',name:'QA ещё одна позиция'});r.seed('bd_assortment_v1',r.assortment);const initialPurchases=r.read('bd_purchase_documents');const created=await r.api.venues.POST(r.request('/api/venues','POST',{name:'Phase4A QA B',businessType:'bar',country:'Россия',city:'Москва',currency:'RUB',timezone:'UTC'}));assert.equal(created.status,201);const secondVenue=(await created.json() as {venue:{id:number}}).venue.id;const secondAccount=Number(r.sqlite.prepare('SELECT data_account_id FROM venues WHERE id=?').get(secondVenue)!.data_account_id);const remap=(v:unknown):unknown=>Array.isArray(v)?v.map(remap):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([key,value])=>[key,key==='venueId'?secondVenue:remap(value)])):v;for(const key of ['bd_assortment_v1','bd_purchase_documents','bd_stock_movements'])r.sqlite.prepare('INSERT INTO domain_data(account_id,store_key,data_json,updated_at) VALUES(?,?,?,?) ON CONFLICT(account_id,store_key) DO UPDATE SET data_json=excluded.data_json').run(secondAccount,key,JSON.stringify(remap(r.read(key))),'2026-10-04T12:00:00Z');let releaseVerify:(()=>void)|null=null;let blockVerify=false;const events:{path:string;method:string;status:number}[]=[];
 const server=createServer(async(req,res)=>{try{
  const url=new URL(req.url||'/',`http://${req.headers.host}`),chunks:Buffer[]=[];for await(const c of req)chunks.push(Buffer.from(c));const body=Buffer.concat(chunks);
  const key=url.pathname.match(/^\/api\/store\/([^/]+)$/)?.[1],signal=decodeURIComponent(url.pathname).match(/^\/api\/management\/cost-signals\/(cost-v1:[^/]+)(\/verify)?$/);
  const routes:Record<string,string>={'/api/access/active-venue':'activeVenue','/api/auth/bootstrap':'bootstrap','/api/restaurants/me':'restaurant','/api/users/me':'users','/api/venues':'venues','/api/store':'bulkStore','/api/business-health':'health','/api/assortment/overview':'overview','/api/management/cost-signals':'costs','/api/management/cost-signals/evaluate':'evaluate','/api/evidence/resolve':'evidence','/api/nomenclature/taxonomy':'taxonomy'};
  const name=key?'store':signal?(signal[2]?'verify':'detail'):routes[url.pathname];
  const request=new Request(url,{method:req.method,headers:req.headers as HeadersInit,...(body.length?{body}:{})});let response:Response;
  if(name==='verify'&&blockVerify){await new Promise<void>(done=>{releaseVerify=done});}
  if(name)response=await r.api[name][req.method||'GET'](request,{params:Promise.resolve({key,id:signal?.[1]})} as never);
  else if(!url.pathname.startsWith('/api/')&&!extname(url.pathname))response=barDoctorResponse();
  else{const file=resolve('public','.'+url.pathname);response=file.startsWith(resolve('public')+'/')&&existsSync(file)?new Response(readFileSync(file),{headers:{'Content-Type':({'.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2'} as Record<string,string>)[extname(file)]||'application/octet-stream'}}):new Response(null,{status:404});}
  if(url.pathname.startsWith('/api/management/')||key==='bd_assortment_v1'&&req.method==='PUT')events.push({path:url.pathname,method:req.method||'GET',status:response.status});
  res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));
 }catch(error){console.error(error);res.writeHead(500);res.end('isolated fixture failure')}});
 await new Promise<void>(done=>server.listen(0,'127.0.0.1',done));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const height=width===390?844:width===820?1180:720;
 const context=await browser.newContext({viewport:{width,height},isMobile:width===390,hasTouch:width===390,locale:'ru-RU'});await context.tracing.start({screenshots:true,snapshots:true});
 await context.addInitScript(({owner,venueId})=>{if(!/^https?:$/.test(location.protocol))return;localStorage.setItem('bd_session',owner.email);localStorage.setItem('bd_session_token',owner.token);if(!localStorage.getItem('bd_active_venue_id'))localStorage.setItem('bd_active_venue_id',String(venueId));},{owner:r.owner,venueId:r.venueId});
 const page=await context.newPage();const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 const capture=async(label:string)=>{const dimensions=await page.evaluate(()=>({innerWidth,innerHeight,clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth}));assert.equal(dimensions.innerWidth,width);assert.ok(dimensions.scrollWidth<=dimensions.clientWidth+1,JSON.stringify({label,...dimensions}));writeFileSync(`${out}/${width}-${label}.json`,JSON.stringify(dimensions));await page.screenshot({path:`${out}/${width}-${label}.png`,fullPage:true});};
 try{
  await page.clock.setFixedTime(new Date('2026-10-04T12:00:00Z'));await page.goto(base+'/home');
  const home=page.locator('[data-cost-surface]');await home.locator('.bd-cost-signal').first().waitFor({timeout:30000});
  const assertUnifiedManagement=async(expectedCost:boolean)=>{const structure=await page.evaluate(()=>{const block=document.querySelector('[data-bd-home-management]'),summary=document.querySelector('[data-bd-home-health-index]'),cost=document.querySelector('[data-cost-surface=home]');return{blocks:document.querySelectorAll('[data-bd-home-management]').length,heading:document.querySelector('#bd-home-management-title-phase4a')?.textContent,summaryCount:document.querySelectorAll('[data-bd-home-health-index]').length,summaryInBlock:!!block&&summary?.closest('[data-bd-home-management]')===block,costCount:document.querySelectorAll('[data-cost-surface=home]').length,costInBlock:!!block&&cost?.closest('[data-bd-home-management]')===block,summaryBorder:summary?getComputedStyle(summary).borderTopWidth:null,summaryShadow:summary?getComputedStyle(summary).boxShadow:null};});assert.equal(structure.blocks,1);assert.equal(structure.heading,'Business Health');assert.equal(structure.summaryCount,1);assert.equal(structure.summaryInBlock,true);assert.equal(structure.costCount,expectedCost?1:0);if(expectedCost)assert.equal(structure.costInBlock,true);assert.equal(structure.summaryBorder,'0px');assert.equal(structure.summaryShadow,'none');};
  const assertHomePriority=async()=>{await page.evaluate(()=>window.scrollTo({top:0,behavior:"instant"}));await page.evaluate(()=>new Promise<void>(done=>requestAnimationFrame(()=>requestAnimationFrame(()=>done()))));const layout=await page.evaluate(()=>{
   const tops=['.bd-cost-home-priority','[data-bd-home-health-index]','[data-bd-home-attention]','.bd-home-money'].map(selector=>document.querySelector(selector)?.getBoundingClientRect().top??Infinity);
   const nav=document.querySelector('[data-bd-primary-navigation]')?.getBoundingClientRect();
   const bottom=Math.min(innerHeight,nav&&nav.width>=innerWidth*.8&&nav.top>innerHeight/2?nav.top:innerHeight);
   const parts=['[data-cost-why]','[data-cost-source]','[data-cost-limitation]','[data-cost-primary-action]'].map(selector=>{const node=document.querySelector(selector),r=node?.getBoundingClientRect();return{selector,top:r?.top,bottom:r?.bottom,height:r?.height,text:node?.textContent}});
   const action=document.querySelector('[data-cost-primary-action]')?.getBoundingClientRect();
   const hit=action?document.elementFromPoint(action.left+action.width/2,action.top+action.height/2)?.closest('button')===document.querySelector('[data-cost-primary-action]'):false;
   return{cost:tops[0],health:tops[1],attention:tops[2],money:tops[3],scrollY,bottom,parts,hit};
  });assert.ok(layout.health<layout.cost&&layout.cost<layout.attention&&layout.attention<layout.money,JSON.stringify(layout));assert.equal(layout.scrollY,0);assert.ok(layout.hit,'Primary cost action is covered by another element');for(const part of layout.parts)assert.ok(part.height&&part.top!>=0&&part.bottom!<=layout.bottom,JSON.stringify(layout));writeFileSync(`${out}/${width}-home-priority-${await page.evaluate(()=>innerHeight)}.json`,JSON.stringify(layout,null,2));};
  await assertUnifiedManagement(true);assert.equal(await home.locator('.bd-cost-home-signal').count(),1);assert.equal(await home.locator('[data-cost-primary-action]').count(),1);assert.ok((await home.locator('[data-cost-count]').innerText()).includes('2'));assert.equal(await page.locator('[data-bd-home-ai]').count(),0);await page.locator('.bd-home-health-score-v332').click();await page.waitForURL(url=>url.pathname==='/health');await page.waitForFunction(()=>document.querySelectorAll('[data-cost-surface] .bd-cost-signal').length===2);await page.goBack();await home.locator('.bd-cost-home-signal').waitFor();await assertHomePriority();await capture('home');await page.screenshot({path:`${out}/${width}-home-first-viewport.png`,fullPage:false});
  if(width===390){await page.setViewportSize({width,height:664});await assertHomePriority();await capture('home-safari-height');await page.screenshot({path:`${out}/390-home-safari-first-viewport.png`,fullPage:false});await page.setViewportSize({width,height});}
  const id=await home.locator('.bd-cost-signal').first().getAttribute('data-signal-id');assert.ok(id);await home.locator('.bd-cost-signal').first().click();
  await page.locator('[data-cost-surface] article').waitFor();assert.equal(await page.locator('[data-cost-surface] article').getAttribute('data-signal-id'),id);await page.getByText('В текущей техкарте нет ингредиентов.',{exact:true}).first().waitFor();await capture('why');
  await page.getByText('Данные и источники',{exact:true}).click();await page.getByRole('button',{name:'Проверить источник: water',exact:true}).click();await page.getByText('Источник проверен; запись соответствует основанию расчёта.',{exact:true}).waitFor();await capture('evidence');
  await page.getByRole('button',{name:'Назад к обзору',exact:true}).click();await page.waitForURL(url=>url.pathname==='/home');await page.locator('[data-bd-home-attention]').first().waitFor();await home.locator('.bd-cost-signal').first().waitFor();assert.equal(await home.locator('.bd-cost-signal').first().getAttribute('data-signal-id'),id);await assertHomePriority();await home.locator('[data-cost-primary-action]').first().click();await page.waitForSelector('[role="dialog"]',{timeout:15000});await capture('editor');
  const dialog=page.locator('[role="dialog"]').last();await dialog.getByRole('button',{name:/Добавить ингредиент/}).click();
  await dialog.getByPlaceholder('Ингредиент или готовый товар').fill('QA вода');await dialog.locator('select').first().selectOption({label:'шт.'});
  await dialog.locator('button').filter({hasText:/Изменить товар|Найти в номенклатуре/}).first().click();await dialog.getByLabel('Поиск по всей номенклатуре').fill('QA вода');await dialog.locator('.bd-tech-card-groups-v375 button').filter({hasText:'QA вода'}).click();
  await dialog.locator('input[type="number"]').first().fill('1');
  if(width===390){await page.setViewportSize({width,height:430});await dialog.locator('input[type="number"]').first().blur();await dialog.locator('input[type="number"]').first().focus();await page.waitForFunction(()=>{const r=document.querySelector('.bd-tech-card-editor-v354 input[type="number"]')?.getBoundingClientRect();return r&&r.top>=0&&r.bottom<=430},{},{timeout:5000});const box=await dialog.locator('input[type="number"]').first().boundingBox();assert.ok(box&&box.y>=0&&box.y+box.height<=430);await capture('keyboard-emulation');await page.setViewportSize({width,height});}
  await capture('correction');const save=dialog.getByRole('button',{name:'Сохранить',exact:true}).filter({visible:true});assert.equal(await save.count(),1);assert.equal(await save.isEnabled(),true);await save.click();await dialog.waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Вернуться к сигналу',exact:true}).click();await page.getByRole('heading',{name:'Проверено: себестоимость рассчитана',exact:true}).first().waitFor();await page.getByText('Стало:',{exact:false}).first().waitFor();await capture('verified');
  const stored=await(await r.detail(id)).json() as {episode:{verificationResult:{after:{value:number};verificationId:string}}};assert.equal(stored.episode.verificationResult.after.value,5);const verificationId=stored.episode.verificationResult.verificationId;
  assert.ok(events.some((event,index)=>event.method==='POST'&&event.path.endsWith('/verify')&&events.slice(0,index).some(e=>e.method==='PUT'&&e.path.includes('bd_assortment_v1'))));
  await page.reload();await page.getByRole('heading',{name:'Проверено: себестоимость рассчитана',exact:true}).first().waitFor();await capture('reload-result');assert.equal((await(await r.detail(id)).json() as typeof stored).episode.verificationResult.verificationId,verificationId);
  await page.goto(base+'/home');await home.locator('.bd-cost-home-signal').waitFor();await assertUnifiedManagement(true);assert.equal(await home.locator('.bd-cost-home-signal').count(),1);assert.ok((await home.locator('[data-cost-count]').innerText()).includes('1'));assert.notEqual(await home.locator('.bd-cost-home-signal').getAttribute('data-signal-id'),id);assert.equal(await home.locator('.bd-cost-signal.verified').count(),0);await capture('remaining-active-home-management');await page.locator('.bd-home-health-score-v332').click();await page.waitForURL(url=>url.pathname==='/health');await page.locator('.bd-cost-signal.verified[data-signal-id="'+id+'"]').click();await page.locator('.bd-cost-result').first().waitFor();
  r.seed('bd_assortment_v1',r.assortment);await page.goto(base+'/home');await page.locator('.bd-cost-signal').filter({hasText:'Себестоимость не рассчитана'}).first().waitFor();const nextId=await page.locator('.bd-cost-signal').filter({hasText:'Себестоимость не рассчитана'}).first().getAttribute('data-signal-id');assert.notEqual(nextId,id);await page.locator('.bd-cost-signal').filter({hasText:'Себестоимость не рассчитана'}).first().click();await page.getByRole('button',{name:'История проверки',exact:true}).click();await page.locator('[data-history-signal="'+id+'"]').waitFor();await capture('recurrence-history');
  r.seed('bd_purchase_documents',[]);r.seed('bd_assortment_v1',r.correct());await page.getByRole('button',{name:'Проверить результат',exact:true}).click();await page.getByText('Себестоимость пока не удалось подтвердить. Сигнал остаётся открытым.',{exact:true}).waitFor();await capture('cannot-verify');
  if(width===820){for(const adjacent of [819,821]){await page.setViewportSize({width:adjacent,height});assert.ok(await page.locator('[data-cost-surface]').isVisible());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1));}await page.setViewportSize({width,height});}
  r.seed('bd_purchase_documents',initialPurchases);blockVerify=true;await page.getByRole('button',{name:'Проверить результат',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-cost-surface] button[disabled]')!==null);await page.locator('[data-bd-venue-trigger]').click();await page.locator('.bd-venue-row').filter({hasText:'Phase4A QA B'}).click();await page.waitForFunction(id=>Number(localStorage.getItem('bd_active_venue_id'))===id,secondVenue);blockVerify=false;(releaseVerify as (()=>void)|null)?.();await page.locator('[data-cost-surface][data-cost-venue="'+secondVenue+'"] .bd-cost-signal').first().waitFor();assert.equal(await page.locator('.bd-cost-result').count(),0);await capture('venue-switch-race');
  await page.locator('[data-bd-venue-trigger]').click();await page.locator('.bd-venue-row').filter({hasText:'Isolated Phase 4A QA'}).click();await page.waitForFunction(id=>Number(localStorage.getItem('bd_active_venue_id'))===id,r.venueId);await page.locator('[data-cost-surface][data-cost-venue="'+r.venueId+'"] .bd-cost-home-signal').waitFor();await page.locator('.bd-home-health-score-v332').click();await page.waitForURL(url=>url.pathname==='/health');await page.locator('.bd-cost-signal.verified').first().waitFor();await page.locator('.bd-cost-signal.verified').first().click();await page.locator('.bd-cost-result').first().waitFor();await capture('venue-return');
  const emptyCreated=await r.api.venues.POST(r.request('/api/venues','POST',{name:'Phase4A empty QA',businessType:'bar',country:'Россия',city:'Москва',currency:'RUB',timezone:'UTC'}));assert.equal(emptyCreated.status,201);const emptyVenue=(await emptyCreated.json() as {venue:{id:number}}).venue.id;const emptyAccount=Number(r.sqlite.prepare('SELECT data_account_id FROM venues WHERE id=?').get(emptyVenue)!.data_account_id);for(const key of ['bd_assortment_v1','bd_purchase_documents','bd_stock_movements'])r.sqlite.prepare('INSERT INTO domain_data(account_id,store_key,data_json,updated_at) VALUES(?,?,?,?) ON CONFLICT(account_id,store_key) DO UPDATE SET data_json=excluded.data_json,updated_at=excluded.updated_at').run(emptyAccount,key,JSON.stringify(key==='bd_assortment_v1'?{menuItems:[],recipes:[],nomenclature:[],stockBalances:[]}:[]),'2026-10-04T12:00:00Z');await page.goto(base+'/home');await page.locator('[data-bd-venue-trigger]').click();await page.locator('.bd-venue-row').filter({hasText:'Phase4A empty QA'}).click();await page.waitForFunction(id=>Number(localStorage.getItem('bd_active_venue_id'))===id,emptyVenue);await page.waitForFunction(()=>document.querySelector('[data-cost-state=STABLE]')!==null);await page.locator('[data-bd-home-health-index]').waitFor();assert.equal(await page.locator('.bd-cost-home-signal').count(),0);assert.ok(await page.locator('.bd-home-money').count());await assertUnifiedManagement(true);await capture('empty-home');r.sqlite.prepare('DELETE FROM domain_data WHERE account_id=? AND store_key=?').run(emptyAccount,'bd_purchase_documents');await page.reload();await page.getByText('Не все источники доступны. Подтверждать исправление пока нельзя.',{exact:true}).waitFor();assert.equal(await page.locator('.bd-cost-home-priority').count(),1);assert.equal(await page.getByText('Нет подтверждённых проблем с обязательной техкартой. Другие проверки доступны ниже.',{exact:true}).count(),0);await assertUnifiedManagement(true);await capture('source-unavailable-home');
  assert.deepEqual(errors,[]);results.push({width,height,clientHash,status:'PASS',id,nextId,unifiedManagementBlock:true,multipleSignalSingleTop:true,scoreToFullHealth:true,topSignalToDetail:true,primaryCtaToCorrection:true,aiDoctorHomeCompetitionRemoved:true,homeCanonicalPriority:true,costActionReachable:true,explicitPrimaryAction:true,emptyHomePreserved:true,unavailableHomeNotHealthy:true,homeBackReturn:true,homeHealthIdentity:true,deterministicWhy:true,evidence:true,realEditorSave:true,authoritativeReread:true,reload:true,recurrenceHistory:true,cannotVerify:true,venueSwitchRace:true,keyboard:width===390?'REDUCED_HEIGHT_EMULATION':'N/A'});

 }catch(error){await page.screenshot({path:`${out}/${width}-failure.png`,fullPage:true});writeFileSync(`${out}/${width}-failure.html`,await page.content());throw error}
 finally{blockVerify=false;(releaseVerify as (()=>void)|null)?.();writeFileSync(`${out}/${width}-events.json`,JSON.stringify(events,null,2));writeFileSync(`${out}/${width}-page-errors.json`,JSON.stringify(errors));await context.tracing.stop({path:`${out}/${width}-trace.zip`});await context.close();await new Promise<void>(done=>server.close(()=>done()));r.close()}
}}finally{await browser.close();assert.equal(createHash('sha256').update(readFileSync('public/assets/index-BQGspy0I.js')).digest('hex'),clientHash,'Prepared client changed during browser verification');writeFileSync(`${out}/results.json`,JSON.stringify({commit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),results},null,2))}
