import { canonicalUserShellAssets } from "../../lib/bardoctor/app-shell";

export function GET(): Response {
  return new Response(`<!doctype html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Касса — BarDoctor</title>
  ${canonicalUserShellAssets()}<link rel="stylesheet" href="/sales-navigation.css?v=sales-scroll-stability"><script src="/sales-navigation.js?v=sales-scroll-stability" defer></script><link rel="stylesheet" href="/cashier.css?v=sales-scroll-stability"><link rel="stylesheet" href="/venue-switcher.css?v=20260826-venue-identity-v297"><script src="/venue-switcher.js?v=20260826-venue-identity-v297" defer></script><script src="/pos-draft.js?v=1" defer></script><script src="/cashier.js?v=sales-scroll-stability" defer></script></head>
  <body class="sales-pos" data-bd-parent-route="/sales-import"><div class="pos-shell"><header class="pos-top"><a href="/sales-import" class="pos-back" aria-label="Вернуться в журнал продаж"><img src="/integration-icons/arrow-left.svg" alt="">Продажи</a><div class="pos-heading"><h1>Касса <span id="venue-name">Заведение</span></h1><div class="pos-context"><span id="shift-title">Выберите кассовую смену</span><span id="employee-name"></span></div></div><span id="connection" role="status">Загрузка данных…</span><div class="bd-standalone-venue-host" data-bd-venue-host></div></header>
  <div id="notice" class="pos-notice" role="status" aria-live="polite">Загрузка кассы…</div><main id="work" hidden><section id="shift-gate" class="pos-gate" hidden><h2>Открытая смена</h2><p id="shift-message"></p><label id="shift-picker-label" hidden>Выберите смену<select id="shift-picker"></select></label><form id="open-shift" hidden><label>Название смены<input id="shift-name" required maxlength="160" placeholder="Например, Вечерняя смена"></label><button type="submit">Открыть смену</button></form><a href="/sales-entry" id="shift-link">Управление сменами</a></section>
  <div id="cashier" class="pos-layout" hidden><div class="pos-mobile-tabs"><button id="show-menu" type="button" aria-pressed="true" aria-controls="menu-panel">Меню</button><button id="show-cart" type="button" aria-pressed="false" aria-controls="cart">Заказ <span id="mobile-count">0</span></button></div><section id="menu-panel" class="pos-menu"><div class="pos-menu-head"><h2>Меню</h2><label class="pos-search"><span class="sr-only">Поиск позиции</span><input id="search" type="search" placeholder="Поиск по меню" autocomplete="off"></label></div><div id="departments" class="pos-tabs" role="group" aria-label="Разделы"></div><div id="categories" class="pos-categories" role="group" aria-label="Категории"></div><p id="search-context" hidden>Поиск по всему меню заведения</p><div id="subcategories" class="pos-categories" role="group" aria-label="Подразделы" hidden></div><div id="menu" class="pos-items"></div></section><section id="cart" class="pos-cart"><div class="pos-cart-head"><h2>Текущий заказ</h2><span id="cart-count">0 позиций</span></div><div id="cart-lines" class="pos-cart-lines"></div><details id="comment-panel" class="pos-comment"><summary>Комментарий к заказу</summary><label><span class="sr-only">Комментарий</span><textarea id="comment" maxlength="500" rows="2" placeholder="Необязательно"></textarea></label></details><div class="pos-cart-foot"><div class="pos-total"><span>Итого</span><strong id="total">0</strong></div><fieldset id="payment"><legend>Оплата</legend><label><input type="radio" name="payment" value="CASH" checked> Наличные</label><label><input type="radio" name="payment" value="CARD_EXTERNAL"> Карта</label><small>Карта — оплата на внешнем терминале</small></fieldset><button id="pay" type="button" class="pos-pay" disabled>Оплатить</button><button id="retry" type="button" hidden>Проверить результат и повторить</button></div></section></div><section id="receipt" class="pos-receipt" hidden><img class="receipt-icon" src="/integration-icons/circle-check.svg" alt=""><h2>Продажа проведена</h2><p class="receipt-subtitle">Сохранена в журнале продаж</p><div id="receipt-detail"></div><button id="new-order" type="button">Новый заказ</button><a id="receipt-sale" class="receipt-link" href="/sales-import">Открыть продажу</a><a class="receipt-journal" href="/sales-import">Вернуться в журнал</a></section></main><button id="order-jump" type="button" hidden aria-label="Перейти к текущему заказу">Заказ · <span id="jump-count">0 шт.</span> · <strong id="jump-total">0</strong> ↓</button></div></body></html>`, {headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store","Content-Security-Policy":"default-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'self'"}});
}
