import { canonicalUserShellAssets } from "../../lib/bardoctor/app-shell";

export function GET(): Response {
  return new Response(`<!doctype html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Касса — BarDoctor</title>
  ${canonicalUserShellAssets()}<link rel="stylesheet" href="/cashier.css?v=pos1"><link rel="stylesheet" href="/venue-switcher.css?v=20260826-venue-identity-v297"><script src="/venue-switcher.js?v=20260826-venue-identity-v297" defer></script><script src="/pos-draft.js?v=1" defer></script><script src="/cashier.js?v=pos1-hardening" defer></script></head>
  <body data-bd-parent-route="/sales-import"><div class="pos-shell"><header class="pos-top"><div><a href="/sales-import" class="pos-back">← Продажи</a><h1>Касса</h1><div class="pos-context"><strong id="venue-name">Заведение</strong><span id="employee-name"></span><span id="connection" role="status">Проверка соединения…</span></div></div><div class="bd-standalone-venue-host" data-bd-venue-host></div></header>
  <div id="notice" class="pos-notice" role="status" aria-live="polite">Загрузка кассы…</div><main id="work" hidden><section id="shift-gate" class="pos-gate" hidden><h2>Открытая смена</h2><p id="shift-message"></p><label id="shift-picker-label" hidden>Выберите смену<select id="shift-picker"></select></label><form id="open-shift" hidden><label>Название смены<input id="shift-name" required maxlength="160" placeholder="Например, Вечерняя смена"></label><button type="submit">Открыть смену</button></form><a href="/sales-entry" id="shift-link">Управление сменами</a></section>
  <div id="cashier" class="pos-layout" hidden><section class="pos-menu"><div class="pos-menu-head"><div><span class="pos-eyebrow">Продажа в смене</span><h2 id="shift-title"></h2></div><label class="pos-search"><span class="sr-only">Поиск позиции</span><input id="search" type="search" placeholder="Поиск по меню" autocomplete="off"></label></div><div id="departments" class="pos-tabs" role="group" aria-label="Разделы"></div><div id="categories" class="pos-categories" role="group" aria-label="Категории"></div><div id="menu" class="pos-items"></div></section><section id="cart" class="pos-cart"><div class="pos-cart-head"><h2>Текущий заказ</h2><span id="cart-count">0 позиций</span></div><div id="cart-lines" class="pos-cart-lines"></div><label class="pos-comment">Комментарий к заказу<textarea id="comment" maxlength="500" rows="2" placeholder="Необязательно"></textarea></label><div class="pos-cart-foot"><div class="pos-total"><span>Итого</span><strong id="total">0</strong></div><fieldset id="payment"><legend>Оплата</legend><label><input type="radio" name="payment" value="CASH" checked> Наличные</label><label><input type="radio" name="payment" value="CARD_EXTERNAL"> Карта · внешняя оплата</label></fieldset><button id="pay" type="button" class="pos-pay" disabled>Оплатить</button><button id="retry" type="button" hidden>Проверить результат и повторить</button></div></section></div><section id="receipt" class="pos-receipt" hidden><h2>Продажа проведена</h2><div id="receipt-detail"></div><button id="new-order" type="button">Новый заказ</button></section></main><button id="order-jump" type="button" aria-label="Перейти к текущему заказу">Заказ · <span id="jump-count">0 шт.</span> · <strong id="jump-total">0</strong> ↓</button></div></body></html>`, {headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store","Content-Security-Policy":"default-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'self'"}});
}
